services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/Catalog/Catalog.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DataBaseSettings__ConnectionString=mongodb://CatalogDb:27017
      - DataBaseSettings__DatabaseName=CatalogDb
      - DataBaseSettings__ProductCollection=Products
      - DataBaseSettings__BrandCollection=Brands
      - DataBaseSettings__TypeCollection=Types
  CatalogDb:
    image: mongo
    container_name: CatalogDb
    ports:
       - "27017:27017"
    volumes:
       - catalogdata:/data/db
  BasketDb:
    image: redis:alpine
    container_name: BasketDb
    restart: always
    ports:
        - "6379:6379"
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.Api/Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CacheSetting__ConnectionString=BasketDb:6379
volumes:
  catalogdata:
    


