services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/Catalog/Catalog.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DataBaseSettings__ConnectionString=mongodb://CatalogDb:27017
      - DataBaseSettings__DatabaseName=CatalogDb
      - DataBaseSettings__ProductCollection=Products
      - DataBaseSettings__BrandCollection=Brands
      - DataBaseSettings__TypeCollection=Types
  CatalogDb:
    image: mongo
    container_name: CatalogDb
    ports:
       - "27017:27017"
    volumes:
       - catalogdata:/data/db
  BasketDb:
    image: redis:alpine
    container_name: BasketDb
    restart: always
    ports:
        - "6379:6379"
  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@1
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DiscountDb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ecommerce.com
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    ports:
     - "5050:80"
    restart: always
    volumes:
      - pgadmin_data:/root/.pgadmin
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.Api/Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CacheSetting__ConnectionString=BasketDb:6379
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.Api/Dockerfile
    container_name: discount.api
    depends_on:
       discountdb:
         condition: service_healthy
    environment:
        - DatabaseSetting__ConnectionString=server=discountdb;port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;
    ports:
       - "8002:8080"

volumes:
  catalogdata:
  postgres_data:
  pgadmin_data:



